# Generated by Django 2.2.5 on 2021-03-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_food_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
