# Generated by Django 2.2.5 on 2021-03-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_food_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='description',
            field=models.TextField(default='Nice Food'),
            preserve_default=False,
        ),
    ]
