# Generated by Django 2.2.5 on 2021-03-30 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_food_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
